title: Security Pentesting News and CTF write ups
description: Security Pentesting News and CTF write ups
author: Ameen Khan
github: https://github.com/spookey0188
about: I'm a Pentester and Security enthusiast. I specialize in networking pentesting and getting more involved in web aplication. 
The purpose of this blog is to give tips on passing the OSCP by writing OSCP like machine write ups and overall pentesting stuff like news,
gadgets, and CTF.
disqus_shortname: Pentesting
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/spookey0188"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://spookey0188.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
